### ISSUE TITLE
Feedback - 32기 박승원

### ISSUE THREAD

**Issue by seungwonpark** [gshslatexintro/LATEX_by_Example-an_introduction_to_general_purpose_LATEX-#3]
ㅁㄴㅇㄹ

**Comment by seungwonpark** [comment]
1. ToC에서 section의 번호와 내용의 띄어쓰기가 어색하다는 느낌이 드는데, 별다른 이유가 없다면 `\usepackage{kotex}`에 hangul 옵션을 적용하는 것을 추천드립니다.
1. '기호 입력하기' 절에서 TeXstudio의 왼쪽 바에 수학 기호 리스트가 있음을 강조해 주었으면 좋겠습니다. 사실 Detexify라는 좋은 웹 앱이 있긴 한데, TeXstudio의 리스트만 있어도 충분합니다.
1. '연산자 입력하기' 절에서 `k_1+k^2=3`을 `k_{1}+k^{2}=3`으로 바꾸었으면 좋겠습니다. `V_{eff}`를 `V_eff`로 썼을 때 어떤 문제가 발생하는지는 잘 아실 겁니다. 저는 위첨자/아래첨자의 내용이 한 글자이더라도 중괄호를 쳐 놓는 것이 좋다고 생각합니다.
1. 저는 미분연산자 `\frac{d}{dx}`를 `\mathrm`와 같이 곧게 써야 한다는 이야기를 어디에서도 들어보지 못했습니다. 적분 뒤에 붙는 `dx`도 마찬가지이고요. 만일 그러하다면(!) reference를 달아 주시기 바랍니다.
1. 나위어 -> 나뉘어 (문법 교정 관련 건은 위치를 별도로 언급하지 않겠습니다. Ctrl+F로 찾아서 고치세요.)
1. 검퓨터 -> 컴퓨터
1. 프로그램, 패키지, 매크로, 등을 -> 프로그램, 패키지, 매크로 등을 (마지막 반점을 없앨 것)
1. 원쪽 -> 왼쪽
1. 켭션 -> 캡션
1. 입려 -> 입력
1. 매장 -> 매 장
1. (온점 뒤에는 항상 띄어쓰기를 해야 합니다. 예를 들어 : ) `... 것이다.이와 같은 ...` -> `... 것이다. 이와 같은 ...`
1. tablar -> tabular
1. '표 삽입하기' 절의 첫 예시의 왼쪽 코드 부분에서, `$` -> `\$`
1. '표 삽입하기' 절의 두 번째 문단 두 번째 문장에서, `ㅣ` -> `l`
1. `&이` -> `&가`, `&은` -> `&는` ('ampersand이' 보다는 'ampersand가' 가 적합해 보입니다.)
1. 화경 -> 환경
1. 정열 -> 정렬
1. '마치며' 절에서, `latex.gs.hs.kr/참여`와 같이, 책의 내용을 편집하기 위해서는 어떻게 해야 하는지 알려주기 위한 간단한 링크나마 첨부해주는 것이 어떨까 합니다.
1. 협회의 정확한 명칭은 `경기과학고등학교 LaTeX 사용자 협회`가 아닌 `경기과학고 TeX 사용자협회` 혹은 `경기과학고 텍 사용자협회` 혹은 `GSHS TeX Society`입니다. 협회 이름이 너무 길어지는 것은 안 좋다고 생각해서...

**Comment by seungwonpark** [comment]
1. `AN INTRODUCTION TO GENERAL PURPOSE LATEX` -> `An Introduction to General Purpose LaTeX`
1. `입문자를 위한 LaTeX 문서 작성의 기초` 의 보다 적절한 번역이 없을까 고민해 봅니다...
1. 책 제목이 너무 길 뿐더러, 내용을 잘 반영하지 못해서 조금 아쉽습니다. 다른 제목을 고민해 보셨으면 좋겠습니다.

**Comment by seungwonpark** [comment]
일단 제 피드백은 여기까지입니다.
이에 대해 궁금한 점 또는 의견이 있다면 댓글 달아주세요.
모두 반영 완료되면 이슈 닫아 주시고요.

**Comment by Namnamseo** [comment]
리포지터리 이름은 굳이 BETA 라는 단어를 가지고 있을 필요는 없다고 생각합니다. 그러한 정보는 `README.md`에 담기는 것으로 충분합니다.

**Comment by EC97B0EAB79C** [comment]
@Namnamseo  아 그건 까먹고 안 바꿈

**Comment by EC97B0EAB79C** [comment]
@seungwonpark  밑의 `입문자를 위한 LaTeX 문서작성`은 부제라서... 일단 너무 길다 느껴지면 다른 이름을 생각해 보겠습니다.

**Comment by seungwonpark** [comment]
피드백 4번 항목을 정정합니다.
정확히는 미분연산자 `d`**만** `\mathrm`으로 쓰고, 그 뒤에 붙는 문자는 원래대로 쓰는 것이 맞다고 합니다. 예를 들어 `\frac{\mathrm{d}}{\mathrm{d}x}`, `\mathrm{d}x`처럼 쓰는 것입니다. (글자 간격은 고려하지 않은 예시입니다.)
Reference : http://www.tug.org/TUGboat/Articles/tb18-1/tb54becc.pdf

물론 처음부터 이걸 다 가르치기는 무리일 것 같으니, 단순히 [commath](http://mirrors.ctan.org/macros/latex/contrib/commath/commath.pdf) 패키지를 사용하면 된다는 것 정도를 알려주면 되지 않을까 생각합니다.
